In [1]:
import re
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter('ignore')

In [ ]:
def delete_useless(contents):

    case1 = re.search('.+?(?=[\.\s\(][a-zA-Z0-9]+?@)', str(contents))
    case2 = re.search('.+?(?=▶)', str(contents))
    case3 = re.search('.+?(?=\w{3}\s?기자)', str(contents))

    if case1 != None :
        contents = case1.group()
    elif case2 != None :
        contents = case2.group()
    elif case3 != None :
        contents = case3.group()
        
    case4 = re.search('기자 \= (.+)', str(contents))
    case5 = re.search('\](.+)', str(contents))
    
    if case4 != None :
        contents = case4.group(1)
    elif case5 != None :
        contents = case5.group(1)
        
    return contents

In [ ]:
df1 = pd.read_csv("Data/theme_news_data/2차전지.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df1.columns = ['data','newspaper','title','contents','link']
df1 = df1['contents']
df1 = df1.drop_duplicates().reset_index()
df1 = df1[0:200]
lst = []
for i in range(len(df1)):
    lst.append(delete_useless(df1.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df1 = pd.DataFrame(lst)
df1['theme'] = '2차전지'
cols = df1.columns.tolist()
cols = cols[-1:] + cols[:-1]
df1 = df1[cols]
df1.columns = ['theme','contents']
df1 = df1[0:100]
df1

In [ ]:
df2 = pd.read_csv("Data/theme_news_data/3d프린터.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df2.columns = ['data','newspaper','title','contents','link']
df2 = df2['contents']
df2 = df2.dropna()
df2 = df2.drop_duplicates().reset_index()
df2 = df2[0:200]
lst = []
for i in range(len(df2)):
    lst.append(delete_useless(df2.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df2 = pd.DataFrame(lst)
df2['theme'] = '3d프린터'
cols = df2.columns.tolist()
cols = cols[-1:] + cols[:-1]
df2 = df2[cols]
df2.columns = ['theme','contents']
df2 = df2[0:100]
df2

In [ ]:
df3 = pd.read_csv("Data/theme_news_data/4대강.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df3.columns = ['data','newspaper','title','contents','link']
df3 = df3['contents']
df3 = df3.dropna()
df3 = df3.drop_duplicates().reset_index()
df3 = df3[0:200]
lst = []
for i in range(len(df3)):
    lst.append(delete_useless(df3.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df3 = pd.DataFrame(lst)
df3['theme'] = '4대강'
cols = df3.columns.tolist()
cols = cols[-1:] + cols[:-1]
df3 = df3[cols]
df3.columns = ['theme','contents']
df3 = df3[0:100]
df3

In [ ]:
df4 = pd.read_csv("Data/theme_news_data/5G.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df4 = df4[3]
df4 = pd.DataFrame(df4)
df4.columns = ['contents']
df4 = df4.dropna()
df4 = df4.drop_duplicates().reset_index()
df4 = df4[0:200]
lst = []
for i in range(len(df4)):
    lst.append(delete_useless(df4.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df4 = pd.DataFrame(lst)
df4['theme'] = '5G'
cols = df4.columns.tolist()
cols = cols[-1:] + cols[:-1]
df4 = df4[cols]
df4.columns = ['theme','contents']
df4 = df4[0:100]
df4

In [ ]:
df5 = pd.read_csv("Data/theme_news_data/AR.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df5 = df5[3]
df5 = pd.DataFrame(df5)
df5.columns = ['contents']
df5 = df5.dropna()
df5 = df5.drop_duplicates().reset_index()
df5 = df5[0:200]
lst = []
for i in range(len(df5)):
    lst.append(delete_useless(df5.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df5 = pd.DataFrame(lst)
df5['theme'] = 'AR'
cols = df5.columns.tolist()
cols = cols[-1:] + cols[:-1]
df5 = df5[cols]
df5.columns = ['theme','contents']
df5 = df5[0:100]
df5

In [ ]:
df6 = pd.read_csv("Data/theme_news_data/CCTV.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df6 = df6[3]
df6 = pd.DataFrame(df6)
df6.columns = ['contents']
df6 = df6.dropna()
df6 = df6.drop_duplicates().reset_index()
df6 = df6[0:200]
lst = []
for i in range(len(df6)):
    lst.append(delete_useless(df6.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df6 = pd.DataFrame(lst)
df6['theme'] = 'CCTV'
cols = df6.columns.tolist()
cols = cols[-1:] + cols[:-1]
df6 = df6[cols]
df6.columns = ['theme','contents']
df6 = df6[0:100]
df6

In [ ]:
df7 = pd.read_csv("Data/theme_news_data/DMZ.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df7 = df7[3]
df7 = pd.DataFrame(df7)
df7.columns = ['contents']
df7 = df7.dropna()
df7 = df7.drop_duplicates().reset_index()
df7 = df7[0:300]
lst = []
for i in range(len(df7)):
    lst.append(delete_useless(df7.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df7 = pd.DataFrame(lst)
df7['theme'] = 'DMZ'
cols = df7.columns.tolist()
cols = cols[-1:] + cols[:-1]
df7 = df7[cols]
df7.columns = ['theme','contents']
df7 = df7[0:100]
df7

In [ ]:
df8 = pd.read_csv("Data/theme_news_data/ESS.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df8 = df8[3]
df8 = pd.DataFrame(df8)
df8.columns = ['contents']
df8 = df8.dropna()
df8 = df8.drop_duplicates().reset_index()
df8 = df8[0:300]
lst = []
for i in range(len(df8)):
    lst.append(delete_useless(df8.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df8 = pd.DataFrame(lst)
df8['theme'] = 'ESS'
cols = df8.columns.tolist()
cols = cols[-1:] + cols[:-1]
df8 = df8[cols]
df8.columns = ['theme','contents']
df8 = df8[0:100]
df8

In [ ]:
df9 = pd.read_csv("Data/theme_news_data/FinTech.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df9 = df9[3]
df9 = pd.DataFrame(df9)
df9.columns = ['contents']
df9 = df9.dropna()
df9 = df9.drop_duplicates().reset_index()
df9 = df9[0:300]
lst = []
for i in range(len(df9)):
    lst.append(delete_useless(df9.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df9 = pd.DataFrame(lst)
df9['theme'] = 'FinTech'
cols = df9.columns.tolist()
cols = cols[-1:] + cols[:-1]
df9 = df9[cols]
df9.columns = ['theme','contents']
df9 = df9[0:100]
df9

In [ ]:
df10 = pd.read_csv("Data/theme_news_data/FPCB.txt", sep='\t', header=None, error_bad_lines=False, engine='python')
df10 = df10[3]
df10 = pd.DataFrame(df10)
df10.columns = ['contents']
df10 = df10.dropna()
df10 = df10.drop_duplicates().reset_index()
df10 = df10[0:300]
lst = []
for i in range(len(df10)):
    lst.append(delete_useless(df10.contents[i]))
for i in lst:
    if len(i) <= 50:
        lst.remove(i)
df10 = pd.DataFrame(lst)
df10['theme'] = 'FPCB'
cols = df10.columns.tolist()
cols = cols[-1:] + cols[:-1]
df10 = df10[cols]
df10.columns = ['theme','contents']
df10 = df10[0:100]
df10

In [ ]:
# for i in range(len(df)):
#     to_compare = df['contents'][i][0:20]
#     new_index = i + 1
#     stopping = True
#     while stopping:
#         if to_compare == df['contents'][new_index][0:20]:
#             df = df.drop(df.index[new_index])
        
#         new_index += 1
        
#         if 
        
#             stopping = False

In [ ]:
final = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10])
final = final.reset_index(drop=True)
final

In [197]:
final.to_csv('sample.csv')

In [5]:
new = pd.read_csv("sample_raw.csv")
new.tail(50)

       Unnamed: 0 Theme Article
28350       28350   0.0     0.0
28351       28351   0.0     0.0
28352       28352   0.0     0.0
28353       28353   0.0     0.0
28354       28354   0.0     0.0
28355       28355   0.0     0.0
28356       28356   0.0     0.0
28357       28357   0.0     0.0
28358       28358   0.0     0.0
28359       28359   0.0     0.0
28360       28360   0.0     0.0
28361       28361   0.0     0.0
28362       28362   0.0     0.0
28363       28363   0.0     0.0
28364       28364   0.0     0.0
28365       28365   0.0     0.0
28366       28366   0.0     0.0
28367       28367   0.0     0.0
28368       28368   0.0     0.0
28369       28369   0.0     0.0
28370       28370   0.0     0.0
28371       28371   0.0     0.0
28372       28372   0.0     0.0
28373       28373   0.0     0.0
28374       28374   0.0     0.0
28375       28375   0.0     0.0
28376       28376   0.0     0.0
28377       28377   0.0     0.0
28378       28378   0.0     0.0
28379       28379   0.0     0.0
28380       28380   0.0     0.0
28381       28381   0.0     0.0
28382       28382   0.0     0.0
28383       28383   0.0     0.0
28384       28384   0.0     0.0
28385       28385   0.0     0.0
28386       28386   0.0     0.0
28387       28387   0.0     0.0
28388       28388   0.0     0.0
28389       28389   0.0     0.0
28390       28390   0.0     0.0
28391       28391   0.0     0.0
28392       28392   0.0     0.0
28393       28393   0.0     0.0
28394       28394   0.0     0.0
28395       28395   0.0     0.0
28396       28396   0.0     0.0
28397       28397   0.0     0.0
28398       28398   0.0     0.0
28399       28399   0.0     0.0