In [72]:
import re
import numpy as np
import pandas as pd
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter('ignore')

In [73]:
def delete_useless(contents):

    case1 = re.search('.+?(?=[\.\s\(][a-zA-Z0-9]+?@)', str(contents))
    case2 = re.search('.+?(?=▶)', str(contents))
    case3 = re.search('.+?(?=\w{3}\s?기자)', str(contents))

    if case1 != None :
        contents = case1.group()
    elif case2 != None :
        contents = case2.group()
    elif case3 != None :
        contents = case3.group()
        
    case4 = re.search('기자 \= (.+)', str(contents))
    case5 = re.search('\](.+)', str(contents))
    
    if case4 != None :
        contents = case4.group(1)
    elif case5 != None :
        contents = case5.group(1)
        
    return contents

In [74]:
def data_arrange_v1(theme):
    
    df = pd.read_csv("Data/theme_news_data/" + theme + ".txt", sep='\t', header=None, error_bad_lines=False, warn_bad_lines=False, engine='python')
    df = pd.DataFrame(df[3]).dropna().drop_duplicates().reset_index(drop=True)
    df.columns = ['contents']
    
    lst = []
    
    for i in range(len(df)):
        lst.append(delete_useless(df.contents[i]))
    
    for i in lst:
        if len(i) <= 100:
            lst.remove(i)
            
    df = pd.DataFrame(lst)
    df['theme'] = theme
    cols = df.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    df = df[cols]
    df.columns = ['theme','contents']
    df = df[0:1000]
    
    return df

In [75]:
def data_arrange_v2(theme):
    
    df = pd.read_csv("Data/theme_news_data/" + theme + ".txt", sep='\t', header=None, error_bad_lines=False, warn_bad_lines=False, engine='python')
    df = pd.DataFrame(df[0]).dropna().drop_duplicates().reset_index(drop=True)
    df.columns = ['contents']
    
    lst = []

    for i in range(len(df)):
        lst.append(delete_useless(df.contents[i]))
    
    for i in lst:
        if len(i) <= 100:
            lst.remove(i)
    
    df = pd.DataFrame(lst)
    df['theme'] = theme
    cols = df.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    df = df[cols]
    df.columns = ['theme','contents']
    df = df[0:1000]
    
    return df

In [76]:
def data_arrange_v3(theme):
    
    df = pd.read_csv("Data/theme_news_data/" + theme + ".txt", sep='\t', header=None, error_bad_lines=False, warn_bad_lines=False, engine='python')
    df = pd.DataFrame(df[1]).dropna().drop_duplicates().reset_index(drop=True)
    df.columns = ['contents']
    
    lst = []

    for i in range(len(df)):
        lst.append(delete_useless(df.contents[i]))
    
    for i in lst:
        if len(i) <= 100:
            lst.remove(i)
    
    df = pd.DataFrame(lst)
    df['theme'] = theme
    cols = df.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    df = df[cols]
    df.columns = ['theme','contents']
    df = df[0:1000]
    
    return df

In [77]:
def data_arrange_v4(theme):
    
    df = pd.read_csv("Data/theme_news_data/" + theme + ".txt", sep='\t', header=None, error_bad_lines=False, warn_bad_lines=False, engine='python')
    df = pd.DataFrame(df.index).dropna().drop_duplicates().reset_index(drop=True)
    df.columns = ['contents']
    
    for i in range(len(df)):
        df['contents'][i] = df['contents'][i][3]
    
    lst = []

    for i in range(len(df)):
        lst.append(delete_useless(df.contents[i]))
    
    for i in lst:
        if len(i) <= 100:
            lst.remove(i)
    
    df = pd.DataFrame(lst)
    df['theme'] = theme
    cols = df.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    df = df[cols]
    df.columns = ['theme','contents']
    df = df[0:1000]
    
    return df

In [80]:
lst = pd.read_csv('Data/data_for_use/theme_company.csv', index_col=0)[0:10]
lst

     Theme                                            Company
0     2차전지  ['천보', '피엔티', '에코프로비엠', ‘유에스티', ‘디에이테크놀로지’, ’피...
1    3D프린터                                        ['하이비젼시스템']
2      4대강  ['코리아에스이', '이화공영', '삼호개발', '우원개발', '코엔텍', '자연과...
3       5G  [‘케이엠더블유’, ’오이솔루션', '대한광통신', 'RFHIC', 'NHN한국사이...
4       AR  ['이랜텍', '나노캠텍', '나무가', '드래곤플라이', '심텍', '팅크웨어',...
5     CCTV                                             ['코콤']
6      DMZ           ['이화공영', '대창스틸', '자연과환경', '코아스', '삼륭물산']
7      ESS  ['상아프론테크', '피엔티', '삼화전기', '엠플러스', '에이치엘비파워', '...
8     FPCB  ['타이거일렉', '필옵틱스', '삼성전기', '아모그린텍', '슈펙스비앤피', '...
9  FinTech  ['NAVER', '카카오', '세틀뱅크', '웹케시', '한국정보통신', '라온시...

In [81]:
for i in tqdm(range(len(lst.Theme.values))):
    try:
        if i == 0:
            df = data_arrange_v1(lst.Theme.values[i])
        else:
            new_df = data_arrange_v1(lst.Theme.values[i])
            df = pd.concat([df, new_df])
    except:
        try:
            new_df = data_arrange_v2(lst.Theme.values[i])
            df = pd.concat([df, new_df])
        except:
            try:
                new_df = data_arrange_v3(lst.Theme.values[i])
                df = pd.concat([df, new_df])
            except:
                try:
                    new_df = data_arrange_v4(lst.Theme.values[i])
                    df = pd.concat([df, new_df])  
                except:
                    print("Error occured: {}".format(lst.Theme.values[i]))

100%|██████████| 10/10 [10:22<00:00, 62.28s/it]

In [82]:
df

       theme                                           contents
0       2차전지   신종 코로나바이러스 감염증(코로나19) 사태로 인한 급락장에서 10대 그룹 시가총...
1       2차전지  다음달 22일 코스닥 이전 상장"자금 수혈되면 2차성장 진입"2차전지 믹싱 업체 티...
2       2차전지   2차 전지 관련주들의 고속질주가 이어지고 있다. 코로나19 여파에도 불구하고 2차...
3       2차전지  이엔플러스가 차세대 2차 전지 핵심 기술이라 불리는 ‘리튬 메탈 전지’와 ‘고체 전...
4       2차전지  이엔플러스가 차세대 2차 전지 핵심 기술이라 불리는 '리튬 메탈 전지'와 '고체 전...
..       ...                                                ...
251  FinTech   Analysts also bet on a turnaround for Samsung...
252  FinTech  Korea Growth Investment Corp (K-Growth), state...
253  FinTech  Kakao Pay, mobile payment service under South ...
254  FinTech   DGB금융그룹이 2011년 설립된 DGB사회공헌재단을 중심으로 지역 주민을 위한 ...
255  FinTech   [영문뉴스 원문 바로가기]  카카오페이가 이달 중 한국판 '위어바오'를 출시한다....

[8265 rows x 2 columns]

In [83]:
#부족한 데이터 확인
grouped = df.groupby('theme', as_index=False).count()
grouped

     theme  contents
0     2차전지      1000
1    3D프린터      1000
2      4대강       718
3       5G      1000
4       AR      1000
5     CCTV      1000
6      DMZ      1000
7      ESS      1000
8     FPCB       291
9  FinTech       256

In [ ]:
#1000개가 안되는 테마들
remover = []
not_full = np.where(df.groupby('theme').count() != 100)
for i in range(len(not_full[0])):
    remover.append(grouped['theme'][not_hund[0][i]])
    
remover

In [ ]:
#삭제
for i in tqdm(range(len(df))):
    if df.theme[i] in remover:
        df = df.drop(index=i)

df = df.reset_index(drop=True)