In [1]:
import pandas as pd
from tqdm import tqdm
import numpy as np
#from konlpy.tag import mecab
from gensim.models import Word2Vec
from scipy.spatial import distance
from gluonnlp.data import SentencepieceTokenizer
from kobert.utils import get_tokenizer
from bs4 import BeautifulSoup as bs
from urllib.request import urlopen
from urllib.parse import quote
import requests
import json
import matplotlib.pyplot as plt
%matplotlib inline
import re
import datetime
from datetime import timedelta

In [2]:
kospi = pd.read_csv("../Data/stock_data/kospi.csv", encoding='cp949')
kosdaq = pd.read_csv("../Data/stock_data/kosdaq.csv", encoding='cp949')

# Load Trained Model

In [3]:
theme_vectors_df = pd.read_csv('theme_vectors_xnorm.csv',index_col=0)

In [4]:
theme_vectors_df

    themes                                            vectors
0     2차전지  [-7096.778220521286, 12871.226797353534, 2587....
1    3D프린터  [10903.843000196677, 18503.521148866625, -3156...
2      4대강  [-8006.077763321286, 7393.415823798161, -24043...
3       5G  [-4483.314872191055, 15860.959652718622, 10811...
4       AR  [4912.215373729239, 17996.481813186198, 649.44...
..     ...                                                ...
163    홈쇼핑  [4915.875856377708, 19768.735261143476, 9870.9...
164    화장품  [13174.82111047738, 23243.34641307546, -2646.9...
165   화학섬유  [-559.1177835975541, 101.75459718890488, -64.1...
166    흑사병  [4110.702740065346, 16790.248373064678, -30731...
167    희토류  [741.8126079159556, 21216.472032813355, -2010....

[168 rows x 2 columns]

In [5]:
theme_vectors_df['vectors'] = theme_vectors_df['vectors'].apply(lambda x: eval(x))

In [6]:
theme_vectors_df['vectors'] = theme_vectors_df['vectors'].apply(lambda x: np.array(x))

# Fit Today News

### Input

In [7]:
real_test = pd.read_csv("../Data/data_for_use/20200629_news_data.csv",index_col=0)
test_date = '2020-06-29'
real_test

                                                    news
0      통신사 관계 없이 이용 가능 24개월 인수형 장기렌탈 서울 뉴시스 오동현 기자 KT...
1      20년 된 전자금융거래법 정비돼야 전자금융 모든 거래 총괄하게 되면 내년 비대면 상...
2      구내식당 모바일스루 서비스…7월 3곳 시범 적용 서울 뉴시스 오동현 기자 모바일 전...
3      소니가 프리미엄 디지털카메라로 분류한 RX100 제품군은 등장 초기에는 존재감이 분...
4      법원 행정처분 집행 정지 인용 지디넷코리아 손예술 기자 법원이 하나금융지주 함영주 ...
...                                                  ...
19938  SNS에 부동산정책 실패 강력 비판 “참모로부터 잘못된 신화 학습 큰일 진보 경제학...
19939  김선혁 교수 한국정치 혁신 촉구 인류 대 바이러스 절체절명 위기 정파간 갈등·대립 ...
19940  4·15 총선서 이미 SNS 유세 등장 합당 온라인투표 공천 화상면접도 돈·조직 기...
19941  여야 합의점 못 찾았지만 29일 오전 10시 다시 회동 법사위 절충안 마련 등 주목...
19942  전날 협상서 의견 접근…법사위원장 절충 가능성 손잡은 국회의장과 여야 원내대표 서울...

[19943 rows x 1 columns]

In [8]:
tok_path = get_tokenizer()
sp  = SentencepieceTokenizer(tok_path)
#stop_words = ['으로', '로도', '지만', '에서', '려는', '하다', '은', '는', '이', '가', '을', '를', '수', '할']
v_dimension = 300
v_window = 8
model = Word2Vec.load('word2vec.model')

using cached model

In [215]:
# news vectors without normalization

def vectorize_without_normal(news):
    hangul = re.compile("[^ㄱ-ㅎㅏ-ㅣ가-힣]+")
    news_words = hangul.sub(' ', news)
    token = sp(news)
    final_tokens = token
    init_v = np.array([0.0]*v_dimension)
    for word in final_tokens:
        word_vectors = model.wv
        if word in word_vectors.vocab:
            v = model.wv[word]
            init_v = init_v + v
    return init_v

In [216]:
# test

def test(news):
    news_vec = vectorize_without_normal(news)
    result = []
    for theme in theme_vectors_df['vectors']:
        cosine = 1 - distance.cosine(theme, news_vec)
        result.append(cosine)
    new_df = pd.DataFrame(data=np.zeros([168,2]), columns=['Theme', 'Result'])
    new_df['Theme'] = theme_vectors_df['themes']
    new_df['Result'] = result

    new_df.sort_values('Result', ascending=False, inplace=True)
    return new_df

In [217]:
lst = []
lst2 = []
for i in tqdm(range(len(real_test))):
    a = real_test['news'][i]
    result = test(a)
    result = result.sort_values(by='Result', ascending=False).reset_index(drop=True)
    theme = result['Theme'][0]
    cosine = result['Result'][0]
    lst.append(theme)
    lst2.append(cosine)

100%|██████████| 19943/19943 [03:30<00:00, 94.76it/s]

In [218]:
df = pd.DataFrame(list(zip(lst, lst2)), columns =['Theme', 'Similarity']) 
df = pd.concat([real_test,df],axis=1)

In [230]:
standard = 0.93
df_filtered = df[df['Similarity']>=standard].reset_index(drop=True)
df_filtered = df_filtered[['Theme','news']]
df_filtered

     Theme                                               news
0      Z플립  8월 말 갤노트20부터 순차 출시…갤폴드라이트 연내 출시는 불투명 지디넷코리아 황정...
1   공공와이파이  와이파이6 중심 공공와이파이 확충사업을 진행하는 서울시가 공공와이파이 시민 모니터링...
2   엔터테인먼트  머니투데이 유승목 기자 CJ ENM 온라인 K컬처 페스티벌 케이콘택트 KCON TA...
3     줄기세포  UNIST 김정범 교수팀 운동기능 회복시키는 환자 맞춤 자가세포치료제 개발 루게릭병...
4     폴더블폰  플래그십 제품과 폴더블폰 출시 시점 분산해 각 제품 관심도 극대화 의도 아이뉴스24...
5     줄기세포  세포 이식 후 향상된 운동능력. 그래픽 김경진 기자 capkim joongang.c...
6      태양광  솔라시도 태양광발전소 전경 사진 한양 제공 이데일리 김미영 기자 중견 건설사인 한양...
7       키즈  아이뉴스24 이현석 기자 네파 친환경 그래픽티셔츠 출시 네파가 여름을 맞아 여름시즌...
8      태양광  에너지 개발사업 진출 첫 성과 신재생 발전사업 확대 교두보 솔라시도 태양광발전소 한...
9      태양광  솔라시도 태양광발전소는 98MW급 태양광 발전설비와 세계 최대 용량 306MWh급의...
10   국가보안법  28일 홍콩 민주화 시위대가 다섯손가락을 활짝 편 채 홍콩보안법 반대 침묵시위를 벌...
11     태양광  부지 조성부터 설계·조달·건설·운영까지 모든 과정 수행 4만5000평 규모 공원 조...
12     태양광  머니투데이 박미주 기자 세계 최대 에너지저장장치 갖춰… 발전소 내 4.5만평 공원 ...
13     태양광  친환경 스마트도시 솔라시도 부지조성부터 설계 조달 건설 O M까지 전과정 수행 전남...
14     태양광  아시아경제 최동현 기자 한양이 한국남부발전·KB자산운용·에너지인프라자산운용 등과 전...
15      방역  코로나 집단감염 우려 확산 최근 2주 감염경로 불명 전체 12% 조사 도중 또 집단...
16    그린뉴딜  민선 7기 반환점 돈 영남권 5개 광역지자체장에 듣는다 민선 7기 반환점을 돈 영남...
17    그린뉴딜  후반기 2년 구상 공개 이철우 경북지사가 29일 도청 다목적홀에서 기자회견을 하고 ...
18      방역  안양 주영광교회·수원 중앙침례교회 추가 확진 발생 서울 왕성교회 3차 감염 사례까지...
19    돼지열병  세종 뉴시스 지난 23일 기준 야생 멧돼지 아프리카돼지열병 ASF 발생 세부현황. ...
20    줄기세포  UNIST 김정범 교수팀 운동기능 회복시키는 자가세포치료제 개발 루게릭병 등 질환에...
21    줄기세포  울산 뉴시스 울산과학기술원 UNIST 생명과학부 김정범 교수 왼쪽 와이현아 연구원....
22    줄기세포  UNIST 김정범 교수팀 운동기능 회복시키는 환자 맞춤 자가세포치료제 개발 루게릭병...
23    해저터널  사상 최대 국고 확보·미래성장 인프라 대폭 확충 흑산공항 건설·광주군공항 이전 답보...
24     태양광  부지 조성부터 설계·조달·건설·운영까지 모든 과정 수행 4만5000평 규모 공원 조...
25      방역  예배 이어 성가모임·MT 등 소모임서도 방역 구멍 한교총도 자제 요청 했지만…통제할...
26      방역  일주일새 교회 관련 3건·소모임 2건 집단발생 식사·노래부르기 등 접촉에 무게…시간...
27      방역  예배 이어 성가모임·MT 등 소모임서도 방역 구멍 한교총도 자제 요청 했지만…통제할...
28   국가보안법  中외교부 어떤 나라도 홍콩 간섭할 권리 없어 美 상원 홍콩자치법 중단 촉구… 반격할...
29   국가보안법  국가 분열 국가정권 전복 등 행위 ‘종신형’ 가능성… 지미 라이 조슈아 웡 법안의 ...
30   국가보안법  보안법 시행 앞두고 또 초강수 反체제 활동 단속근거 쓰일 듯 중국 전인대 상무위원회...
31   국가보안법  7월 1일 홍콩 반환일 전 시행될 듯 미국 등 홍콩 제재 수위 주목 중 외교부 홍콩...
32   국가보안법  머니투데이 베이징 중국 김명룡 특파원 홍콩반환일 인 7월1일 맞춰 발효될 듯…종신형...
33   국가보안법  지난 5월 28일 중국 베이징 인민대회당에서 13기 전국인민대표대회 전인대 3차 전...
34   국가보안법  中 초안 심의 돌입… 홍콩내 반중 시위 직접적 여파 예상 소급적용 가능성 제기… 미...
35   국가보안법  마카오 국가보안법 최고 형량 30년보다 더 세질 듯 법 위반자 과거 행적 기소 때 ...
36   국가보안법  요미우리신문 홍콩 내 민주화 세력 진압 의지 홍콩 국가보안법 오는 30일 최종 통과...
37   국가보안법  보안법 철회ㆍ인권 보호 요구하는 홍콩 시위대 사진 AP 중국 전국인민대표대회 전인대...
38   국가보안법  홍콩보안법에 항의하는 현수막을 들고 있는 홍콩 시민 중국 전국인민대표대회 전인대 상...
39   국가보안법  홍콩반환일 7월1일 발효 유력 홍콩 경찰 7월1일 집회 23년 만에 첫 금지 한국경...
40   국가보안법  중국 전인대 30일 오전 의결 전망 전인대 대표 회개하면 비소급…추가 위반시 과거 ...
41   국가보안법  최고 형량 종신형 가능성…홍콩 시위대·미국 반발 예상 보안법 철회ㆍ인권 보호 요구하...
42   국가보안법  中 이르면 내일 홍콩보안법 선포… 7월1일 집회서 충돌 벌어질 수도 중국이 이르면 ...
43   국가보안법  홍콩 국보법 발효 앞두고 견제… 中 “내정간섭 말라” 즉각 반발 코로나로 美 입국제...

In [232]:
df_final = df_filtered.groupby('Theme', as_index=False).count().sort_values(by='news',ascending=False)
df_final = df_final[(df_final['news']>=1) & (df_final['news']<6)].reset_index(drop=True)
df_final

    Theme  news
0      방역     5
1    줄기세포     5
2    그린뉴딜     2
3     Z플립     1
4  공공와이파이     1
5    돼지열병     1
6  엔터테인먼트     1
7      키즈     1
8    폴더블폰     1
9    해저터널     1

# Make Portfolio

In [233]:
def target_com(theme, theme_list):
    company_list=theme_list[theme_list['Theme']==theme]['Company'].iloc[0]
    company_list=str(company_list).replace('[','').replace(']','').replace("\'",'').replace(' ', '').replace('‘','').replace('’','').split(',')
    
    target_theme = {}
    for target in company_list:
        try:
            code = kosdaq[kosdaq['기업명']==target].iloc[0]['종목코드']
            code = str(code).zfill(6)
            target_theme[code] = target
        except:
            try:
                code = kospi[kospi['기업명']==target].iloc[0]['종목코드']
                code = str(code).zfill(6)
                target_theme[code] = target
            except: pass
        
    return target_theme, company_list

In [234]:
def target_(target_comapny):
    target_theme = {}
    for target in target_company:
        try:
            code = kosdaq[kosdaq['기업명']==target].iloc[0]['종목코드']
            code = str(code).zfill(6)
        except:
            code = kospi[kospi['기업명']==target].iloc[0]['종목코드']
            code = str(code).zfill(6)
        target_theme[code] = target
        
    return target_theme

In [235]:
def date_convert(date):
    end_date = date
    
    def date_by_deducting_business_days(from_date):
        business_days_to_deduct = 6
        current_date = from_date
        while business_days_to_deduct > 0:
            current_date += datetime.timedelta(days=-1)
            weekday = current_date.weekday()
            if weekday >= 5: # sunday = 6
                continue
            business_days_to_deduct -= 1
        return current_date

    convert_end_date = datetime.datetime.strptime(date,'%Y-%m-%d').date()
    start_date=datetime.date.strftime(date_by_deducting_business_days(convert_end_date),'%Y-%m-%d')
    
    return start_date, end_date

In [179]:
def date_format(d):
    d = str(d).replace('-', '.')
    yyyy = int(d.split('.')[0])
    mm = int(d.split('.')[1])
    dd = int(d.split('.')[2])
    
    this_date = dt.date(yyyy, mm, dd)
    return this_date

In [180]:
def date_format(d=''):
    if d != '':
        this_date = pd.to_datetime(d).date()
    else:
        this_date = pd.Timestamp.today().date()
    return (this_date)

In [181]:
def stock_info(stock_cd):
    url_float = 'http://companyinfo.stock.naver.com/v1/company/c1010001.aspx?cmp_cd=' + stock_cd
    source = urlopen(url_float).read()
    soup = bs(source, 'lxml')
    
    tmp = soup.find(id='cTB11').find_all('tr')[6].td.text
    tmp = tmp.replace('\r', '').replace('\n','').replace('\t','')
    tmp = re.split('/', tmp)
                   
    outstanding = tmp[0].replace(',','').replace('주','').replace(' ','')
    outstanding = int(outstanding)
                   
    floating = tmp[1].replace(' ','').replace('%','')
    floating = float(floating)
                   
    name = soup.find(id='pArea').find('div').find('div').find('tr').find('td').find('span').text
    
    stock_outstanding[stock_cd] = outstanding
    stock_floating[stock_cd] = floating
    stock_name[stock_cd] = name

In [182]:
def historical_index_naver(index_cd, start_date='', end_date='', page_n=1, last_page=0):
    
    if start_date:
        start_date = date_format(start_date)
    else:
        start_date = datetime.date.today()
    if end_date:
        end_date = date_format(end_date)+datetime.timedelta(days=-1)
    else:
        end_date = datetime.date.today()
    
    naver_index = 'http://finance.naver.com/sise/sise_index_day.nhn?code=' + index_cd + '&page=' + str(page_n)
    
    source = urlopen(naver_index).read()
    source = bs(source, 'lxml')
    
    dates = source.find_all('td', class_='date')
    prices = source.find_all('td', class_='number_1')
    historical_prices = dict()

    
    for n in range(len(dates)):
        if dates[n].text.split('.')[0].isdigit():
            
            # Handling date
            this_date = dates[n].text
            this_date = date_format(this_date)
            
            if this_date <= end_date and this_date >= start_date:
                
                # Handling closing price
                this_close = prices[n*4].text
                this_close = this_close.replace(',','')
                this_close = float(this_close)
                
                historical_prices[this_date] = this_close

            elif this_date < start_date:
                return historical_prices
            
    
    # Navigating page
    if last_page == 0:
        last_page = source.find('td', class_='pgRR').find('a')['href']
        
        last_page = last_page.split('&')[1]
        last_page = last_page.split('=')[1]
        last_page = int(last_page)
        
    if page_n < last_page:
        page_n += 1
        historical_index_naver(index_cd, start_date, end_date, page_n, last_page)
        
    return historical_prices

In [183]:
def historical_stock_naver(stock_cd, start_date='', end_date='', page_n=1, last_page=0):
    
    
    if start_date:
        start_date = date_format(start_date)
    else:
        start_date = datetime.date.today()
    if end_date:
        end_date = date_format(end_date)+datetime.timedelta(days=-1)
    else:
        end_date = datetime.date.today()
    
    naver_stock = 'http://finance.naver.com/item/sise_day.nhn?code=' + stock_cd + '&page=' + str(page_n)
    
    source = urlopen(naver_stock).read()
    #source = requests.get(naver_stock)
    source = bs(source, 'lxml')
    
    dates = source.find_all('span', class_='tah p10 gray03')
    prices = source.find_all('td', class_='num')
    historical_prices = dict()

    for n in range(len(dates)):
        
        if len(dates) > 0:
            
            # Handling date
            this_date = dates[n].text
            this_date = date_format(this_date)
            
            if this_date <= end_date and this_date >= start_date:
                
                # Handling closing price
                this_close = prices[n*6].text
                this_close = this_close.replace(',','')
                this_close = float(this_close)
                
                historical_prices[this_date] = this_close

            elif this_date < start_date:
                return historical_prices
            
    
    # Navigating page
    if last_page == 0:
        last_page = source.find('td', class_='pgRR').find('a')['href']
        last_page = last_page.split('&')[1]
        last_page = last_page.split('=')[1]
        last_page = int(last_page)
        
    if page_n < last_page:
        page_n += 1
        historical_stock_naver(stock_cd, start_date, end_date, page_n, last_page)
        
    return historical_prices

In [184]:
def threshold(data):
    if data < -0.05 or data > 0.05: return False
    else : return True

In [185]:
def stock_get_info(target_theme):
    stock_outstanding = dict()
    stock_floating = dict()
    stock_name = dict()
    for stock_cd in target_theme.keys():
        stock_info(stock_cd)
    
    return stock_outstanding, stock_floating, stock_name

In [186]:
def theme_historical_price(target_theme, stard_date, end_date):
    theme_historical_prices = dict()
    

    for stock_cd in target_theme.keys():
        historical_prices = historical_stock_naver(stock_cd, start_date, end_date)

        theme_historical_prices[stock_cd] = historical_prices

    theme_historical_price = pd.DataFrame(theme_historical_prices)
    theme_historical_price.sort_index(axis=1, inplace=True)

    theme_historical_price = theme_historical_price.fillna(method='ffill')
    if theme_historical_price.isnull().values.any():
        theme_historical_price = theme_historical_price.fillna(method='bfill')

    #theme_historical_price['kospi200'] = historical_index_naver('KPI200', start_date, end_date).values()
    
    return theme_historical_price

In [187]:
def make_portfolio(theme, test_date):
    #stock_outstanding = 0; stock_floating = 0; stock_name = 0;
    start_date, end_date = date_convert(test_date)
    theme_list=pd.read_csv("../Data/data_for_use/theme_company_cleansed_final.csv",index_col=0)
    target_theme, company_list = target_com(theme, theme_list)
    #stock_outstanding, stock_floating, stock_name = stock_get_info(target_theme)
    theme_price = theme_historical_price(target_theme, start_date, end_date)

    df = theme_price
    for i in range(len(df.index)-1):
        df.iloc[i] = (theme_price.iloc[i] - theme_price.iloc[i+1])/theme_price.iloc[i]
    try:
        df.drop(index=[df.index[-1]], inplace=True)
    except: pass
    
    print('\n')
    print('오늘의 추천테마는 : {}'.format(theme))
    print('해당 테마의 추천 종목은 :')
    for i in range(len(company_list)):
        standard = 1
        try:
            for j in range(len(df.index)-1):
                standard *= threshold(df.iloc[:, i][j])

            if standard == 1 : 
                print('{} : {}'.format(df.columns[i], target_theme[df.columns[i]]))
        except:pass

In [236]:
for i in df_final.Theme:
    make_portfolio(i, test_date)

오늘의 추천테마는 : 방역
해당 테마의 추천 종목은 :
011000 : 진원생명과학
012690 : 모나리자
043200 : 파루


오늘의 추천테마는 : 줄기세포
해당 테마의 추천 종목은 :
007390 : 네이처셀
028300 : 에이치엘비
032980 : 바이온
034940 : 조아제약
052260 : SK바이오랜드
067630 : 에이치엘비생명과학
091090 : 세원셀론텍
203690 : 프로스테믹스
271980 : 제일약품


오늘의 추천테마는 : 그린뉴딜
해당 테마의 추천 종목은 :
033530 : 세종공업
038870 : 에코바이오
042370 : 비츠로테크
093370 : 후성


오늘의 추천테마는 : Z플립
해당 테마의 추천 종목은 :
027580 : 상보
060720 : KH바텍
106240 : 파인테크닉스


오늘의 추천테마는 : 공공와이파이
해당 테마의 추천 종목은 :
031310 : 아이즈비전


오늘의 추천테마는 : 돼지열병
해당 테마의 추천 종목은 :
001790 : 대한제당
003380 : 하림지주
003540 : 대신증권
005930 : 삼성전자
005940 : NH투자증권
006980 : 우성사료
015890 : 태경산업
018620 : 우진비앤지
027710 : 팜스토리
027740 : 마니커
027970 : 세하
033250 : 체시스
035290 : 더블유에프엠
036480 : 대성미생물
041960 : 코미팜
043200 : 파루
044960 : 이글벳
052670 : 제일바이오
054670 : 대한뉴팜
072020 : 중앙백신
073560 : 우리손에프앤지
086060 : 진바이오텍
136480 : 하림
136490 : 선진
195500 : 마니커에프앤지
198440 : 고려시멘트
208140 : 정다운
900340 : 윙입푸드


오늘의 추천테마는 : 엔터테인먼트
해당 테마의 추천 종목은 :
036420 : 제이콘텐트리
041510 : 에스엠
054780 : 키이스트
068050 : 팬엔터테인먼트
122870 : 와이지엔터테인먼트
173940 : 에프엔씨엔터
182360 : 큐브엔터
253450 : 스튜디오드래곤


오늘의 추천테마는 : 키즈
해당 테마의 추천 종목은 :
039830 : 오로라
066910 : 손오공
159580 : 제로투세븐
215480 : 토박스코리아


오늘의 추천테마는 : 폴더블폰
해당 테마의 추천 종목은 :
055490 : 테이팩스
060720 : KH바텍
106240 : 파인테크닉스
131760 : 파인텍
148150 : 세경하이테크
179900 : 유티아이


오늘의 추천테마는 : 해저터널
해당 테마의 추천 종목은 :
028100 : 동아지질
060370 : KT서브마린