# Extracting Theme List

In [1]:
import pandas as pd
import numpy as np
import re
from tqdm import tqdm

In [2]:
df = pd.read_csv("naver_news_crawler/data/final_data.csv", index_col=0)
df.head(10)

,title,contents
0,"두나무 증권플러스 비상장, 5월 핫 키워드는 게임&핀테크 테마주","게임 테마주 여전한 인기, 한국카카오은행·비바리퍼블리카 등 핀테크 테마주도 급상승 ..."
1,게맛살 회사가 조 바이든 美 대선 테마주라고?,8일 조 바이든 미국 민주당 대선후보의 ‘테마주’로 묶여 상한가를 친 기업의 사업보...
2,"'이낙연 테마주'로 각광받던 회사, 상폐 직전에 부활한 사연",주가조작 시기에는 '이낙연(전 국무총리) 테마주'라는 사실무근의 소문이 돌면서 한때...
3,"엔터테인먼트3사 주가 모두 상승, '방탄소년단 테마주' 대체로 올라",방탄소년단 테마주'로 묶이는 회사 주가도 대부분 올랐다. 경남제약 주가는 14.9%...
4,신용융자 몰린 주식 대부분 테마주…'투자 주의보',하지만 신용융자가 급증한 종목 대부분이 변동성 높은 테마주여서 투자에 주의가 필요하...
5,"'자동차 테마주' 강세 쌍용차, 16.36% 상승세","'자동차 테마주' 강세 쌍용차, 16.36% 상승세 '자동차 테마주' 강세 쌍용차,..."
6,"김종인 ""통합당에 대선주자 있나?""에 홍정욱 테마주 KNN 들썩",의원의 테마주로 분류되는 KNN(058400)이 29일 강세를 보이고 있다. KNN...
7,"'하이난 자유무역항 테마주', 중국 증시 다크호스로 주목",하이난 테마주의 인기도 뜨겁다. 지난 2018년 4월 하이난 경제특구 건설 30주년...
8,[특징주] 코로나19 재확산에 구충제테마주 '껑충',▲ 5일 종가 기준 코로나19 재확산으로 급등하고 있는 구충제 테마주. 시가총액순....
9,"중국 '노점상 경제' 열풍, 증시에선 '테마주'로 자금 밀물",이와 함께 최근 중국 증시에서도 '노점상 경제' 테마주는 연일 주가 상승세를 연출하...

In [3]:
kospi = pd.read_csv("data/kospi.csv", index_col=0, encoding='cp949')
kosdaq = pd.read_csv("data/kosdaq.csv", index_col=0, encoding='cp949')

In [4]:
company_list = pd.concat([kospi[['종목코드', '기업명']], kosdaq[['종목코드', '기업명']]], axis=0)
company_list = company_list.sort_values('기업명').reset_index().drop(columns='번호')
company_list

        종목코드     기업명
0      60310      3S
1      95570  AJ네트웍스
2       6840   AK홀딩스
3      54620  APS홀딩스
4     265520   AP시스템
...      ...     ...
2200  189980  흥국에프엔비
2201     540    흥국화재
2202    3280    흥아해운
2203   37440      희림
2204  238490      힘스

[2205 rows x 2 columns]

In [5]:
df.isnull().sum()

title       0
contents    1
dtype: int64

In [6]:
df.drop(index=[1224], inplace=True)
df.reset_index(inplace=True)

In [ ]:
def theme_check(txt):
    return txt.endswith('한', '에', '는', '등', '며', '서')

In [24]:
dic={}

for i in tqdm(range(len(df))):
    for company in company_list['기업명']:
        if company in df['contents'][i]:
            theme = 0
            try:
                theme_list = re.findall("[\s,\'](\w+?)\s[테마주,관련주]", df['title'][i])
                theme = re.findall("[\s,\'](\w+?)\s[테마주,관련주]", df['title'][i])[0]
                if theme.endswith(('한', '에', '는', '등', '며')):
                    theme = re.findall("[\s,\'](\w+?)\s[테마주,관련주]", df['contents'][i])[0]
                    if theme.endswith(('한', '에', '는', '등', '며')):
                        theme = re.findall("[\s,\'](\w+?)\s[테마주,관련주]", df['contents'][i])[1]
                try: dic[theme].append(company)
                except KeyError: dic[theme] = [company]
            except: pass

100%|██████████| 7791/7791 [04:51<00:00, 26.73it/s]

In [25]:
# 중복 제거

cpy = dic

for key, value in dic.items():
    dic[key] = list(set(value))

In [26]:
theme_company_list = pd.DataFrame.from_dict(data=dic, orient='index')
theme_company_list

,0,1,2,3,4,5,6,7,8,9,...,298,299,300,301,302,303,304,305,306,307
대선,한성기업,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
방탄소년단,넷마블,SK텔레콤,디피씨,드림어스컴퍼니,경남제약,엘비세미콘,소리바다,키이스트,초록뱀,SK,...,None,None,None,None,None,None,None,None,None,None
홍정욱,고려산업,KNN,벽산,남선알미늄,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
혼조,퍼스텍,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
유승민,아세아,국일신동,삼일,아세아텍,삼일기업공사,대신정보통신,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
두산그룹,두산솔루스,두산퓨얼셀,두산인프라코어,두산,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
韓,파미셀,진원생명과학,부광약품,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
남선알미늄티케이케미칼,남선알미늄,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
선출되면서,티비씨,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
방사광가속기,비츠로테크,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [40]:
theme_company_list.to_csv('data/theme_company_list.csv')